version: '3.8'

services:
  web:
    build:
      context: .
    container_name: container-lab
    ports:
      - 8000:8000
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: "db"
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

  db:
    image: postgres:15-alpine
    container_name: database
    volumes:
      - ./src/api/db/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
        POSTGRES_USER: "postgres"
        POSTGRES_PASSWORD: "postgres"
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5